base_url = "lyra95.github.io"

compile_sass = true

build_search_index = true

[markdown]
highlight_code = true

[languages.ko]
title = "Sapienta Ducet Ad Astra"
[languages.en]
title = "Sapienta Ducet Ad Astra"

[search]
include_title = true
include_description = false
include_path = false
include_content = true
index_format = "elasticlunr_javascript"

[extra]
# Put all your custom variables here
