name: Build Test
on:
  workflow_call:
    inputs:
      REF:
        type: string
        required: true
jobs:
  # .github/workflows/deploy.yaml의 deploy job과 쌍을 이뤄야함
  deploy:
    runs-on: ubuntu-22.04
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.REF }}
      - uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "0.4.28"
      - run: mdbook build
