name: Deploy
on:
  workflow_dispatch:
    inputs:
      REF:
        type: string
        required: false
        default: main
jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
    with:
      REF: ${{ inputs.REF }}
  deploy:
    runs-on: ubuntu-22.04
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.REF }}
      - uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "0.4.28"
      - run: mdbook build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
