name: Pull Request
on:
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
    with:
      REF: ${{ github.sha }}
  build-test:
    needs: [lint]
    uses: ./.github/workflows/build-test.yaml
    with:
      REF: ${{ github.sha }}
